{% set name = "simple-parsing" %}
{% set version = "0.1.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/simple_parsing-{{ version }}.tar.gz
  sha256: 71b00c78e8b67f93cdc640f6999304e6a352d0ceef180b27d6a9d866f76c8041

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pre-commit
    - python >=3.6
  run:
    - docstring_parser ~=0.15
    - python >=3.6
    - typing_inspect

test:
  imports:
    - simple_parsing
    - simple_parsing.helpers
    - simple_parsing.wrappers
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/lebrice/SimpleParsing
  summary: A small utility for simplifying and cleaning up argument parsing scripts.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
