{% set name = "simple-parsing" %}
{% set version = "0.1.6" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/simple_parsing-{{ version }}.tar.gz
  sha256: dad192e9633515a5627e343106636590a39a5ce85f6c47ced43507044ed98956

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - poetry-dynamic-versioning >=1.0.0,<2.0.0
    - python {{ python_min }}
  run:
    - docstring_parser ~=0.15
    - python >={{ python_min }},<4.0
    - typing_extensions >=4.5.0

test:
  imports:
    - simple_parsing
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/lebrice/SimpleParsing
  summary: A small utility for simplifying and cleaning up argument parsing scripts.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
