{% set name = "simple-parsing" %}
{% set version = "0.1.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/simple_parsing-{{ version }}.tar.gz
  sha256: 312300327d8f0beb61b6419500423bd335be8b83da66f733e9c67c6c18341ae8

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pre-commit
    - python >=3.7
  run:
    - docstring_parser ~=0.15
    - python >=3.7
    - typing_extensions >=4.5.0

test:
  imports:
    - simple_parsing
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/lebrice/SimpleParsing
  summary: A small utility for simplifying and cleaning up argument parsing scripts.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
