{% set name = "simple-parsing" %}
{% set version = "0.0.18" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/simple_parsing-{{ version }}.tar.gz
  sha256: 8cdd8e2c5b7bf99d579027a6d12ef88218a1dc9b121cd5762820565a734eee82

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pre-commit
    - python >=3.6
  run:
    - dataclasses
    - python >=3.6
    - typing_inspect

test:
  imports:
    - simple_parsing
    - simple_parsing.helpers
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/lebrice/SimpleParsing
  summary: A small utility for simplifying and cleaning up argument parsing scripts.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
