{% set name = "simple-parsing" %}
{% set version = "0.0.21" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/simple_parsing-{{ version }}.tar.gz
  sha256: 541d2582b20885af537f7086a91bf082440456ccfcbb83e7dd9b201d2d5dc177

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pre-commit
    - python >=3.6
  run:
    - dataclasses
    - python >=3.6
    - typing_inspect

test:
  imports:
    - simple_parsing
    - simple_parsing.helpers
    - simple_parsing.wrappers
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/lebrice/SimpleParsing
  summary: A small utility for simplifying and cleaning up argument parsing scripts.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
