{% set name = "simple-parsing" %}
{% set version = "0.0.16.post2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/simple_parsing-{{ version }}.tar.gz
  sha256: e1b1dd83e770feca7b78c3caf471ee9d9ad7b71ada43149594a63616ffb7d640

build:
  number: 0
  skip: true  # [py2k]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - dataclasses  # [py<37]
    - python
    - typing_inspect

test:
  imports:
    - simple_parsing
    - simple_parsing.helpers
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/lebrice/SimpleParsing
  summary: A small utility for simplifying and cleaning up argument parsing scripts.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
