{% set name = "simple-parsing" %}
{% set version = "0.1.7" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/simple_parsing-{{ version }}.tar.gz
  sha256: 225e6b35252d68f7894716101fe3bd7e6dd3d30ab7b1c3c023f77a42dbe1336f

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: True  #[py<38]

requirements:
  host:
    - pip
    - python
    # Required for pip to import the PEP 517 backend during metadata preparation
    - poetry-core >=1.0.0
    - poetry-dynamic-versioning >=1.0.0,<2.0.0
  run:
    - docstring_parser >=0.15,<1.dev0
    - python
    - typing_extensions >=4.5.0

test:
  imports:
    - simple_parsing
  commands:
    - pip check
  requires:
    - pip
    - python

about:
  home: https://github.com/lebrice/SimpleParsing
  summary: A small utility for simplifying and cleaning up argument parsing scripts.
  description: |
    simple-parsing allows you to transform your ugly argparse scripts into beautifully structured, strongly typed little works of art.
    This isn't a fancy, complicated new command-line tool either, this simply adds new features to plain-old argparse!
    Using dataclasses, simple-parsing makes it easier to share and reuse command-line arguments - no more copy pasting!
  license: MIT
  license_file: LICENSE
  license_family: MIT
  dev_url: https://github.com/lebrice/SimpleParsing
  doc_url: https://github.com/lebrice/SimpleParsing

extra:
  recipe-maintainers:
    - thewchan
